import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";
import dynamic from "next/dynamic";

const SSESubscriber = dynamic(
  () => import("@/app/components/notification/SSESubscriber"),
  {
    ssr: false
  }
);

export const metadata = {
  title: "고민친구",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="manifest" href="/manifest.json" />
      <meta name="theme-color" content="#ffeb86"/>
      <meta name="apple-mobile-web-app-capable" content="yes"></meta>
      <link rel="apple-touch-startup-image" href="/splashscreens/ipad_splash.png"></link>
      <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1125x2436.png"/>
      <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-750x1334.png"/>
      <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1242x2208.png"/>
      <link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-640x1136.png"/>
      <link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1536x2048.png"/>
      <link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1668x2224.png"/>
      <link rel="apple-touch-startup-image" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-2048x2732.png"/>
      <body>
        <Header />
        <div className="container">
          <SSESubscriber />
          <div>{children}</div>
        </div>
        <Footer />
      </body>
      
    </html>
  );
}
