
import Header from './components/header'
import './globals.css'

export const metadata = {
  title: '고민친구',
  description: 'Generated by create next app',
  icons:{
    icon:'/favicon.ico'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <div className='relative'>{children}</div>
      </body>
    </html>
  )
}
